### ISSUE TITLE
Bapp store build/Submission

### ISSUE THREAD

**Issue by 0x27** [moloch--/CSP-Bypass#1]
Just a suggestion - it would be cool to submit this to the Bapp store so it can be seamlessly installed from within the Burp environment by just clicking on it and all that :)

**Comment by moloch--** [comment]
I plan to eventually, I'd like to polish it a bit more before submitting.

**Comment by mandatoryprogrammer** [comment]
@moloch-- don't let your dreams be dreams, push that thing to the store TODAY!

**Comment by moloch--** [comment]
Accepted as of ~Feb. 2017
